### ISSUE TITLE
List command failed with Proton-6.21-GE-2

### ISSUE THREAD

**Issue by JustCryen** [AUNaseef/protonup#21]
I've just installed this program, I'm not sure if this is an issue only on my side but if not, I hope it'll be useful.

```
❯ protonup -l
Proton-6.08-GE-1 - 1.4 GiB
Proton-5.11-GE-3-MF - 1.2 GiB
Proton-5.09-GE-6-ST - 1.2 GiB
Proton-5.08-GE-2-MF - 1.2 GiB
Proton-6.01-GE-1 - 1.2 GiB
Proton-6.19-GE-1 - 1.5 GiB
Proton-6.14-GE-2 - 1.5 GiB
Proton-6.01-GE-2 - 1.2 GiB
Proton-6.10-GE-1 - 1.4 GiB
Proton-5.00-7-alyx-2 - 1.4 GiB
Proton-5.11-GE-1-MF - 1.2 GiB
Proton-6.16-GE-1 - 1.5 GiB
Traceback (most recent call last):
  File "/usr/bin/protonup", line 33, in <module>
    sys.exit(load_entry_point('protonup==0.1.4', 'console_scripts', 'protonup')())
  File "/usr/lib/python3.10/site-packages/protonup/__init__.py", line 4, in main
    return main()
  File "/usr/lib/python3.10/site-packages/protonup/cli.py", line 44, in main
    print(f"{item} - {readable_size(folder_size(_install_directory + item))}")
  File "/usr/lib/python3.10/site-packages/protonup/utilities.py", line 70, in folder_size
    size += os.path.getsize(os.path.join(root, file))
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/cryen/.steam/root/compatibilitytools.d/Proton-6.21-GE-2/files/share/default_pfx/drive_c/windows/system32/uiautomationcore.dll'
```

**Comment by bpc1** [comment]
I see you updated to python 3.10 too. The python update broke basically all packages that use python. For protonup rebuilding it fixed the errors for me.

**Comment by JustCryen** [comment]
Yeah but which package to download?
I updated python yesterday but I've downloaded `protonup` today ;/
That's a really frustrating problem with python… updates break everything.

**Comment by bpc1** [comment]
I rebuilt `protonup-git`

**Comment by AUNaseef** [comment]
@JustCryen Can you remove the pip version and install protonup from source and see if the problem persists?

**Comment by JustCryen** [comment]
This was from source.
Anyway, I've rebuilt it but now I have even more problems…
This time --releases doesn't work either (previously it worked)
```
❯ protonup -l
Traceback (most recent call last):
  File "/usr/bin/protonup", line 33, in <module>
    sys.exit(load_entry_point('protonup==0.1.4', 'console_scripts', 'protonup')())
  File "/home/cryen/.local/lib/python3.10/site-packages/protonup-0.1.4-py3.10.egg/protonup/__init__.py", line 4, in main
  File "/home/cryen/.local/lib/python3.10/site-packages/protonup-0.1.4-py3.10.egg/protonup/cli.py", line 32, in main
AttributeError: 'Namespace' object has no attribute 'rem'
```
At least `protonup -h` still seems to be working.

**Comment by AUNaseef** [comment]
I missed some code that was still using `rem` after the command was changed to `remove`, my bad. fixed now.

**Comment by JustCryen** [comment]
Weardly enough, I've installed new proton version with protonup (Proton-7.0rc2-GE-1) but it still fails on Proton-6.21-GE-2
```
❯ protonup -l
Proton-6.08-GE-1 - 1.4 GiB
Proton-5.11-GE-3-MF - 1.2 GiB
Proton-5.09-GE-6-ST - 1.2 GiB
Proton-7.0rc2-GE-1 - 1.5 GiB
Proton-5.08-GE-2-MF - 1.2 GiB
Proton-6.01-GE-1 - 1.2 GiB
Proton-6.19-GE-1 - 1.5 GiB
Proton-6.14-GE-2 - 1.5 GiB
Proton-6.01-GE-2 - 1.2 GiB
Proton-6.10-GE-1 - 1.4 GiB
Proton-5.00-7-alyx-2 - 1.4 GiB
Proton-5.11-GE-1-MF - 1.2 GiB
Proton-6.16-GE-1 - 1.5 GiB
Traceback (most recent call last):
  File "/usr/bin/protonup", line 33, in <module>
    sys.exit(load_entry_point('protonup==0.1.4', 'console_scripts', 'protonup')())
  File "/home/cryen/.local/lib/python3.10/site-packages/protonup-0.1.4-py3.10.egg/protonup/__init__.py", line 4, in main
  File "/home/cryen/.local/lib/python3.10/site-packages/protonup-0.1.4-py3.10.egg/protonup/cli.py", line 44, in main
  File "/home/cryen/.local/lib/python3.10/site-packages/protonup-0.1.4-py3.10.egg/protonup/utilities.py", line 70, in folder_size
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/cryen/.steam/root/compatibilitytools.d/Proton-6.21-GE-2/files/share/default_pfx/drive_c/windows/system32/uiautomationcore.dll'
```
The file 
```
/home/cryen/.steam/root/compatibilitytools.d/Proton-6.21-GE-/files/share/default_pfx/drive_c/windows/system32/uiautomationcore.dll
```
exists but when I try to read it with another program (bat) I also get `No such file or directory (os error 2)`
I think it's either an issue with this specific version of proton or maybe a corrupted download.

Also, is it possible to make the `list` command work with alphabetical order?

**Comment by JustCryen** [comment]
Yup, it was just a corrupted download.
Reinstalled this Proton version and everything works now.
